fuge_global:
  tail: true
  monitor: true
  monitor_excludes:
    - '**/node_modules/**'
    - '**/.git/**'
    - '*.log'
  env_file:
    - './telegram.env'


api:
  type: process
  path: ../01_api/src
  run: 'node index.js'
  monitor: true

session:
  type: process
  path: ../05_session/src
  run: 'node index.js'
  monitor: true

user-store:
  type: process
  path: ../07_user-store/src
  run: 'node index.js'
  monitor: true
  environment:
    - DB=ecov

classroom-store:
  type: process
  path: ../07_classroom-store/src
  run: 'node index.js'
  monitor: true
  environment:
    - DB=ecov

course-store:
  type: process
  path: ../07_course-store/src
  run: 'node index.js'
  monitor: false
  environment:
    - DB=ecov

file-store:
  type: process
  path: ../06_file-store/src
  run: 'node index.js'
  monitor: true
  environment:
    - DB=ecov

service-discovery:
  type: process
  path: ../04_service-discovery/src
  run: 'node index.js'
  monitor: true
  environment:
    - DB=ecov
