fuge_global:
  tail: true
  monitor: true
  monitor_excludes:
    - '**/node_modules/**'
    - '**/.git/**'
    - '*.log'
  env_file:
    - './telegram.env'

    
api:
  type: process
  path: ../01_api/src
  run: 'node index.js'
  monitor: true


classroom-store:
  type: process
  path: ../07_classroom-store/src
  run: 'node index.js'
  monitor: true
  environment:
    - DB=ecov

course-store:
  type: process
  path: ../07_course-store/src
  run: 'node index.js'
  monitor: true
  environment:
    - DB=ecov
