
version: '3.3'


services:

  frontend:
    image: registry.gitlab.com/fdt2k/e20/frontend
    networks:
      - web
    env_file:
        - front.env
    deploy:
      placement:
          constraints:
           - node.role == manager


networks:
  web:
    external:
      name: proxy
