node:
  build: ./
  environment:
    - VIRTUAL_HOST=${FQDN}
    - LETSENCRYPT_HOST=${FQDN}
    - LETSENCRYPT_EMAIL=fabien@ditore.ch
    - DB_SERVERS=172.17.0.2
    - DB_USER=saladin
    - DB_PASS=gYYF9bobmi
    - DB=saladin
    - LISTEN_PORT=80
#  volumes:
#  - /srv/saladin-client/dist:/usr/share/nginx/html:ro
  expose:
  - 80
  restart: unless-stopped
